### PR TITLE
Hopefully fixed the problem with the weird names by using a id

### PR DESCRIPTION
**Pull request by Wissididom**
Proof:
not_found_handling
get_names_by_id

### CODE REVIEW

**Comment by GeorgeCiesinski** [comment]
@Wissididom Can you go into more details about this fix? 

- What is the issue this is fixing?
- Is `catch <pokemon_id>` optional or a hard replacement for names? Can you still guess names?
- Is this meant to be a optional game mode (guess id instead of name)?

**Comment by Wissididom** [comment]
1. This fixes the problem, that `pokemon[0].split('-').toLowerCase();` didn't work for some pokemon because i use the id at getting the names
2. This is optional because i just added the id as an additional language, you can still guess in english and other languages:
guess_in_english

**Comment by GeorgeCiesinski** [comment]
Thanks @Wissididom and one more question. In the scenario where the Pokemon name doesn't work due to the dash issue, do you have to then guess using the id, or is the issue fixed now so you can guess the Pokemon name normally? I can see in your screenshot that this works with Lugia, but I am wondering about those specific problem Pokemon whose name splits incorrectly. Can you guess those using English or another language, or do you have to use the ID in that case?

**Comment by Wissididom** [comment]
I have just tested it with the problematic tapu koko. I replaced `let pokemonNames = [pokemon.url.replace(/.+\/(\d+)\//g, '$1')];` with `let pokemonNames = ['785'/*pokemon.url.replace(/.+\/(\d+)\//g, '$1')*/];` to test it so the sprite and artwork is wrong but the names worked:
proof_tapu_koko

**Comment by GeorgeCiesinski** [comment]
Beautiful, wonderful job! 

I just wanted to make sure this all works, I'll merge this in.

**Pull request merged**
