### PR TITLE
Feature/update readme

### PR DESCRIPTION
**Pull request by GeorgeCiesinski**
Updated README to remove word soup and to make installation instructions complete and easy to understand. 

I also modified the `example.env` file so that it is ready to go for docker and only really needs to be changed to run in a local node environment. 

Command and role information has been moved to newly created wiki pages which is still in progress. I am planning to use [this](https://github.com/adriantanasa/github-wiki-sidebar) to generate a nicer wiki soon as there is a lot of commands and use cases and I wanted to describe them in more detail on the wiki. 

@Wissididom Can you check to see if my instructions for creating the env files, running locally and in docker are complete and correct? I am not sure if anyone needs to run `npm install` as I am still pretty new to node. Feel free to add suggestions in order to make the README complete and friendly for new collaborators.

### CODE REVIEW

**Comment by GeorgeCiesinski** [comment]
I forgot to add this earlier, but I also replaced the steps from regular markdown format to html format as it is easier to modify instructions without having to go down the list of numbers and manually change them. This way, the ordered list does the work for us and renumbers the instructions after any steps are added or removed.

**Comment by Wissididom** [comment]
here are things I noticed so far:
> Create the .env and docker.env files:
> > Step 3 It is not called `POSTGRES_PASS` it is called `POSTGRES_PASSWORD`

> Adding Slash Commands:
> > You need to execute `npm install` before executing `node setupCommands`, because for registering slash commands I use discord.js for communication with Discord and dotenv to get the discord-token

> Run Locally:
> > Postgres also has a login method which does not work (ident) where it uses the user account you're logged in with. It usually works out of the box because Postgres usually creates a user called postgres on installation when using the psql command line tool, just not with pg nor Sequelize

> One thing I forgot to put in the README in the first place is, that you should be able to just use the property `DATABASE_URL` instead of `POSTGRES_DB`, `POSTGRES_USER`, `POSTGRES_PASSWORD` and `POSTGRES_PORT`, see below

```js
if (process.env['DATABASE_URL']) {
	db = new Sequelize(process.env['DATABASE_URL']);
} else {
	db = new Sequelize(process.env['POSTGRES_DB'], process.env['POSTGRES_USER'], process.env['POSTGRES_PASSWORD'], {
		host: process.env['POSTGRES_HOST'],
		port: parseInt(process.env['POSTGRES_PORT']),
		dialect: 'postgres' // one of 'mysql' | 'mariadb' | 'postgres' | 'mssql'
	});
}
```

**Comment by GeorgeCiesinski** [comment]
@Wissididom I updated the changes you mentioned above. Can you check one more time before I merge? I hope I understood you correctly regarding the DATABASE_URL and sequalize constructor.

**Comment by GeorgeCiesinski** [comment]
Comment test

**Comment by GeorgeCiesinski** [comment]
Comment test

**Pull request merged**
