### PR TITLE
Added the ability to catch by clicking a button

### PR DESCRIPTION
**Pull request by Wissididom**
Simply added logic for an Discord Modal and bypassed the problem I had for `/catch` that you have to decide if you want to have your initial response ephemeral or not and my logic took longer than 3 seconds to even decide that because I wanted it to be ephemeral everytime except it is a correct guess. Below an demo video:
https://user-images.githubusercontent.com/30803034/196045661-d9e87580-29ee-4146-92ac-a2839860975f.mp4

### CODE REVIEW

**Comment by GeorgeCiesinski** [comment]
That is impressive, I love the changes!

Same as the other PR, can you check if README needs any update and merge if not?

**Comment by Wissididom** [comment]
I need to add the new way to catch to the README and at some point in time I want to remove the `/catch` command because it has a worse UX than the button and modal from this PR. Especially because of the ephemeral decision problem.
I don't know if I adjust the PR today or in the next few days. We'll see.

**Comment by GeorgeCiesinski** [comment]
No worries!

**Comment by Wissididom** [comment]
borreLore please check the `README.md` for any mistakes in building the sentence, its grammar and if you see it fitting better somewhere else in the `README.md`.

TODOs for me (I guess):
1. Remove "Type /catch `pokemon:_____` with the correct pokemon name to catch this pokemon!" or replace with something else in the bots `/explore` response
2. Update catch.png after 1. has been changed

**Review by GeorgeCiesinski — APPROVED** [review]

**Pull request merged**
