### PR TITLE
Lightning Round

### LINKED ISSUE #34: Gameplay feature: Lightning Round
(Issue should be expanded before starting changes)

# Describe the new feature
Add a new command to start a lightning round, where a new pokemon will be generated upon each successful guess. This game mode would be toggled on/off, or would automatically expire after x number of loops, where x is provided alongside the command. 

## Planning
1. Add a command for the lightning round with an optional loops parameter: 

### Example: Toggle Lightning round on/off
`!lightning`

### Example: Turn on Lightning round for 5 loops
`!lightning 5`

### Current Mode
During lightning round, a part of the message should show a helpful icon like lightning strike, and inform the players that the current mode is lightning round in order to prevent it from being left on longer than intended.

## Organization

Game modes might need to be organized into a new file that imports necessary functions as more game modes might be added eventually.

### LINKED ISSUE #108: /reveal results in a crash and restart
# Describe the bug
Running `/reveal` results in 

> poke-bot is thinking...

and spins continuously. It doesn't fail until a very long time passes, but it outputs error into console: 

```javascript
poke-guesser-bot       | /usr/src/app/reveal.js:20
poke-guesser-bot       |                     let lowercaseName = encounter[i].name.toLowerCase();
poke-guesser-bot       |                                                           ^
poke-guesser-bot       | 
poke-guesser-bot       | TypeError: Cannot read properties of undefined (reading 'toLowerCase')
poke-guesser-bot       |     at Commands.reveal (/usr/src/app/reveal.js:20:59)
poke-guesser-bot       |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
poke-guesser-bot       | 
poke-guesser-bot       | Node.js v19.7.0
poke-guesser-bot exited with code 1
poke-guesser-bot       | 
poke-guesser-bot       | > poke-guesser-bot@1.0.0 start
poke-guesser-bot       | > node index.js
poke-guesser-bot       | 
poke-guesser-bot       | Logged in as poke-bot#3409!
```

## To Reproduce
1. Start poke-bot
2. Run `/explore` to generate pokemon
3. Run `/reveal` to result in error

## Expected behavior
`/reveal` is supposed to output the pokemon

## Desktop (fill in or erase if not applicable):
 - OS: MacOS Ventura 13.4
 - Docker

## Possible solutions
The cause of the issue is unknown. It is possible poke-api is providing a different object than what it used to show. Another possible place to look is the below documentation: 

https://sequelize.org/docs/v6/core-concepts/getters-setters-virtuals/#getters

https://sequelize.org/docs/v6/core-concepts/model-querying-finders/

### PR DESCRIPTION
**Pull request by Wissididom**
Closes #34
To make it work, I had to fix #108 as well

### CODE REVIEW

**Comment by GeorgeCiesinski** [comment]
Does this need review & approval, or should I wait until it is no longer in WIP?

**Comment by Wissididom** [comment]
Actually I began doing it, but I think I haven't finished working on it. Actually I haven't worked on it since I made the first commit.

I will make a PR in a bit tho with a Github Action that checks formatting with Prettier. That PR will have +3751 -2941 where most of it was made by running `npx prettier --write .`

**Comment by Wissididom** [comment]
I made the same changes as here in the new develop branch to not having to resolve merge conflicts. I than forgot to commit when force pushing to lightning-rounds which is why the PR got closed.
Will work on it later, I just wanted to resolve the merge conflicts for now.

**Comment by Wissididom** [comment]
My Test was successful, I think it is ready for review now: 
https://github.com/GeorgeCiesinski/poke-guesser-bot/assets/30803034/22612ac1-577c-4002-927e-13f16b02b6ea

**Comment by GeorgeCiesinski** [comment]
Merging this PR as the commands issue is just a **me** problem right now and will be resolved in #116 once we decide how to implement SetupCommands.

**Pull request merged**
